services:
  backend:
    build:
      context: ./app/backend
    restart: unless-stopped
    environment:
      - PORT=5055
    volumes:
      - nis_data:/app/data
    ports:
      - "5243:5055"

  web:
    build:
      context: ./app/frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "6789:8080"

volumes:
  nis_data:

